"use client";
import { Accessibility, AlertTriangle, BarChart3, Droplets, Footprints, Layers3, Map, UsersRound } from "lucide-react";
import { useState } from "react";
import { CityMapView } from "@/components/CityMapView";
import { cityPriorities } from "@/lib/data";
const sidebarItems=[{id:"overview",label:"نظرة عامة",icon:BarChart3},{id:"map",label:"الخريطة",icon:Map},{id:"heat",label:"الإجهاد الحراري",icon:Footprints},{id:"crowd",label:"الازدحام",icon:UsersRound},{id:"accessibility",label:"الإتاحة",icon:Accessibility},{id:"services",label:"الخدمات",icon:Droplets},{id:"reports",label:"البلاغات",icon:AlertTriangle},{id:"interventions",label:"التدخلات",icon:Layers3}] as const;
type SectionId=(typeof sidebarItems)[number]["id"];
const sectionCopy:Record<SectionId,{title:string;description:string}>={overview:{title:"حالة نطاق التجربة",description:"قراءة مجمعة للراحة، الحركة، الإتاحة والخدمات في النطاق التجريبي."},map:{title:"الخريطة الحضرية",description:"تصفح نقاط التجربة على خريطة الشوارع أو صور الأقمار الصناعية."},heat:{title:"الإجهاد الحراري",description:"يعرض طبقة نقاط الحرارة التجريبية فقط."},crowd:{title:"الازدحام",description:"يعرض نقاط كثافة المشاة التجريبية فقط."},accessibility:{title:"الإتاحة",description:"يعرض ملاحظات الإتاحة التجريبية على الخريطة."},services:{title:"الخدمات",description:"يعرض نقاط نقص الخدمات التجريبية في النطاق."},reports:{title:"البلاغات",description:"ملخص بلاغات المجتمع التجريبية في نطاق العرض."},interventions:{title:"التدخلات",description:"أولويات التدخل المقترحة بناءً على بيانات العرض الحالية."}};
const periodLabel:Record<string,string>={today:"اليوم",week:"آخر 7 أيام",month:"آخر 30 يومًا"};
export default function CityDashboardPage(){const[active,setActive]=useState<SectionId>("overview");const[period,setPeriod]=useState("today");const copy=sectionCopy[active];return <main className="city-layout"><aside className="city-sidebar"><h2>لوحة المدينة</h2><nav>{sidebarItems.map(({id,label,icon:Icon})=><button key={id} type="button" className={active===id?"is-active":""} onClick={()=>setActive(id)}><Icon size={17}/>{label}</button>)}</nav></aside><section className="city-main"><div className="city-mobile-tabs">{sidebarItems.map(({id,label})=><button key={id} type="button" className={active===id?"is-active":""} onClick={()=>setActive(id)}>{label}</button>)}</div><div className="city-topline"><div><h1>{copy.title}</h1><p>{copy.description}</p></div><select className="city-filter" value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">اليوم</option><option value="week">آخر 7 أيام</option><option value="month">آخر 30 يومًا</option></select></div><div className="dashboard-demo-notice">الفترة المحددة: <strong>{periodLabel[period]}</strong>. طبقات وأرقام لوحة المدينة حاليًا بيانات عرض فقط؛ الأزرار والفلترة تعمل، لكننا لا نسميها بيانات حية حتى نوصل مصادر البلدية/الحساسات.</div><div className="city-overview"><div className="city-map-panel"><CityMapView focus={active}/></div><div className="city-sidepanel"><div className="city-metrics"><div className="city-metric"><span>متوسط الراحة*</span><strong>78</strong></div><div className="city-metric"><span>بلاغات نشطة*</span><strong>126</strong></div><div className="city-metric"><span>نقاط أولوية عالية*</span><strong>18</strong></div><div className="city-metric"><span>مشاركات متحقق منها*</span><strong>71%</strong></div></div><div className="priority-list"><h2>{active==="interventions"?"التدخلات المقترحة":"أعلى أولويات التدخل"}</h2>{cityPriorities.map(item=><button type="button" className="priority-row priority-row--button" key={item.name} onClick={()=>setActive(item.issue==="ازدحام"?"crowd":item.issue==="إتاحة"?"accessibility":item.issue==="نقص خدمات"?"services":"heat")}><div><strong>{item.name}</strong><span>{item.issue} · {item.reports} ملاحظة</span></div><div className="priority-score">{item.score}</div></button>)}</div></div></div><section className="dashboard-section"><h2>المؤشرات التشغيلية التجريبية · {periodLabel[period]}</h2><div className="table-scroll"><table className="data-table"><thead><tr><th>المؤشر</th><th>الحالة الحالية</th><th>مقارنة بخط الأساس</th><th>ملاحظة</th></tr></thead><tbody><tr><td>المسارات ذات الراحة العالية</td><td>64%*</td><td>+8%*</td><td>بيانات عرض</td></tr><tr><td>المرور عبر نقاط الاختناق</td><td>21%*</td><td>-5%*</td><td>بيانات عرض</td></tr><tr><td>الملاحظات المتحقق منها</td><td>71%*</td><td>+11%*</td><td>بيانات عرض</td></tr><tr><td>زمن الرصد إلى الإجراء</td><td>19 ساعة*</td><td>-3 ساعات*</td><td>بيانات عرض</td></tr></tbody></table></div></section></section></main>}
